# Generated by Django 3.2.3 on 2021-05-21 15:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rateable', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rateable',
            unique_together={('owner', 'name')},
        ),
    ]
